services:
  oauth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_PROVIDER=google
      - OAUTH2_PROXY_EMAIL_DOMAINS=tinybird.co
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8080/oauth2/callback
      - OAUTH2_PROXY_METRICS_ADDRESS=:8081
      - OAUTH2_PROXY_UPSTREAMS=http://golinks:8000
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
  golinks:
    build:
      context: .
      dockerfile: Dockerfile